### ISSUE TITLE
themes.languages.current constants don't work

### ISSUE THREAD

**Issue by web2date** [typo3-themes/themes#116]
TYPO3 6.2 / theme_bootstrap 1.4.6 / themes 2.5.0 / theme_gridelements 0.6.3
Even after setting everything in Themes Editor the chosen constants don't show up either in Typoscript Object Browser or FE
 [language] = {$themes.languages.default.flag}
  [locale_all] = {$themes.languages.default.isoCode}.UTF-8
  [htmlTag_langKey] = {$themes.languages.default.isoCodeHtml} 

maybe constants in constants didn't work ext/themes/Configuration/TypoScript/constants.txt

**Comment by tdeuling** [comment]
HTML lang attribute is fixed with commit:
https://github.com/typo3-themes/themes_gridelements/commit/1e2f4419281880a473885ba1e0cc584b36db93de

The only problems we had found was related to the constants-viewhelper.
The problem in detail is, that constants which are setted with other constants, are not correctly returned.
For example:
```
themes.languages.current.label = {$themes.languages.default.label}
```
returns:
```
{$themes.languages.default.label}
```
from the viewhelper.

So, the viewhelper needs a replacement for those constants in constants.
