### ISSUE TITLE
your selected Theme seems to not support 1 Layout 

### ISSUE THREAD

**Issue by NickIQTIG** [typo3-themes/themes#121]
I try to reproduce the code described in your book "Typo3 Theming and Distribution", but all I get is this error. 
As I can see, every template (except the error template) in ext\themes\Resources\Private\Templates\Theme has only this entry:
\<f:render partial="Errors/Error" arguments="{message:'your selected Theme seems to not support {templateName} Layout'}"/\>. So changing the template in the backend has no effect, right? But my own template is not recognized, too.

**Comment by t-zimmermann** [comment]
This sounds like a problem I allready had. By the way: The title of Error Message for me seems to show, that you are working on the 6.2, right?
In the 7 branch, this message is already more precise. But I also had these Problems, because I played with selfmade backendLayouts and made some errors. As a solution I already made a pull-request for that. https://github.com/t-zimmermann/themes/commit/ca080e36e51bd323f1e10252df43dd0277f00dda 
If you created your own backendlayout and you are sure to have selected the right one, please verify that the identifier in your backend-configuration reads exactly (capitalization inclusive!) like the filename of your theme-template.
Your message seems like you missed the part with the identifier in your your backend-configurationfile.
Maybe, there are more reasons for this message, but this was my solution.

**Comment by kaystrobach** [comment]
@NickIQTIG the syntax of backendlayouts was changed after releasign the book (we do now follow the official 7.6 syntax in all TYPO3 versions).

Please refer to https://github.com/typo3-themes/themes_gridelements/blob/master/Configuration/BackendLayouts/Content.pagets to get the right syntax for defining a layout.
And please refer to https://github.com/typo3-themes/theme_bootstrap/tree/master/Resources/Private/Templates/Theme how to render it.

**Additionally i want to give the following hint to you.**

Sticking to the predefined layouts gives you the power of theme switching, if you leave that standard a lateron switch can produce unpredictable results (content in wrong columns etc.).
Please also read the existing layouts carefully and stick as near as possible to the function each column has (makes switching easy)
