### ISSUE TITLE
Installation via composer failed

### ISSUE THREAD

**Issue by fazzyx** [typo3-themes/themes#183]
Hi,

there is no version tag for 8.7.2 and the installation via composer failed by
typo3-themes/themes >=8.7.2,<8.8 -> no matching package found
but there is a dependency to >=8.7.2 from theme_bootstrap4.

Best regards,

Claus

**Comment by fazzyx** [comment]
In other words: can you please set a Tag with version 8.7.2 that this can be installed via composer.
Thank you.

**Comment by kaystrobach** [comment]
Will do - we will also sync it with TER, that’s why it takes a bit longer

**Comment by pniederlag** [comment]
Would be cool. :->

**Comment by pniederlag** [comment]
ping. it seems meanwhile you have dependencies for 8.7.6 while 8.7.0 is still the most recent tag.

**Comment by pniederlag** [comment]
@kaystrobach Many THX! composer.json of themes on master yields 8.7.6, https://github.com/typo3-themes/themes/blob/master/composer.json so that's probably why master of theme_bootstrap requires 8.7.6 https://github.com/typo3-themes/theme_bootstrap4/blob/master/composer.json

Unfortunatly composer will always use the composer.json from the tip of a branch, even if you require specific sha's.

For example it's impossible to get this to work:

`composer require typo3-themes/themes:dev-master#e19353178 typo3-themes/theme-bootstrap4:dev-master#2e8ea37`

Not even an alias will help...

```
themes:dev-master#e19353178 as 8.7.2
theme-bootstrap4:dev-master#2e8ea37 as 0.5.1
```

The only easy way out is to set tags on git...
... or stay on track with master development... which is not so cool for production ;)
@tdeuling would be awesome if you could add tags for theme_bootstrap4 as well.

**Comment by kaystrobach** [comment]
Just added https://github.com/typo3-themes/themes/releases/tag/8.7.6 ... as this was definitely our problem.

Anyway composer.jsons should never have a version inside, this was an ugly workaround for TYPO3 6.2

**Comment by kaystrobach** [comment]
@pniederlag  so it should work now -> please verify, than i would close the issue.

Also with having our pipelines on gitlab we can identify and avoid these kind of problems ... more to come soon ... travis is just more work if you anyway work with gitlab all day long.

**Comment by pniederlag** [comment]
@kaystrobach thx for your efforts. Tag 8.7.2 contains a composer.json with a version 8.7.6 flag... hmmm...

**Comment by pniederlag** [comment]
@kaystrobach git show e19353178 seems to be more logic for tag 8.7.2 than git show ee40d5078285

**Comment by kaystrobach** [comment]
you are right - changed and pushed

**Comment by kaystrobach** [comment]
closing for now, feel free to reopen, if you find any other issues.
