### ISSUE TITLE
themesIndependent should be disabled by default

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes#61]
themesIndependent should be disabled by default - otherwise it could be a little bit confusing

**Comment by astehlik** [comment]
The independent mode is not only confusing but broken:

The problem is the configuration in:
https://github.com/typo3-themes/themes/blob/master/ext_tables.php#L134

It will only be loaded when the TCA cache is not loaded, see:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Core/Bootstrap.php#L1022

So for non cached requests the configuration of Themes is never added and you will get a blank page. I think this needs to be moved to ext_localconf.php to work.

**Comment by kaystrobach** [comment]
themes independent ist disabled by default from now on 
https://github.com/typo3-themes/themes/blob/master/ext_conf_template.txt
