### ISSUE TITLE
Typoscript template integration prevents overrides

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes#91]
Hi, 
this is a great step forward.
A major drawback of including theme's typoscript as the lastest template in the templates stack it that this prevent any integration with another extension.

What if i want to override any value of it ? 
Simply impossible without altering the theme. Not realy what i call modulable.

What i mean is for eg:bootstrap, themes are only sets of less variables changed on top of the main bootstrap.
So you can have a bootstrap base, and simply override some less variables to get flatly, yeti ... themes. 
This means 1 bootstrap base extension and one for each set of less variables.

**Comment by Bunnyfield** [comment]
That's exactly how themes work - you get the themes base, on top of that you get the base package for a certain framework - i.e. bootstrap or foundation - and on top of that you get a theme extension like i.e theme_bootstrap_highland, which is currently work in progress. On top of that you can add as many other extensions to the theme parts you already installed as you like. So actually I don't get your point, but maybe you can clarify a bit what your problem is?

**Comment by s-leger** [comment]
Say i have an extension overriding some of the bootstrap_package theme parts.
So i setup themes, bootstrap_package, then the overriding extension (currently without any theme integration). 
As result  themes do load bootstrap_package static templates after the one of my extension, and override it.
How can i make themes aware of my extension ?
How can i manage the loading order of extensions overriding parameters of another ones under themes ?

**Comment by kaystrobach** [comment]
Please do not rely on the bootstrap_package as base,  it's not generic enough.  See theme_bootstrap_slate as an example. It depends on theme_bootstrap

**Comment by Bunnyfield** [comment]
The trick is to do it the other way around. Instead of making your extension aware of themes, you should have an extension that is aware of your extension and themes.

Reason: Making your extension aware of a certain framework base package or a theme based on that package would make your extension depend on that theme. Switching a theme later on would be close to impossible then. So this would be exactly what we wanted to avoid with themes.

Instead you should create a kind of "mini theme adapter extension" that depends on both, the theme you are using AND your extension. Staying with the bootstrap package example and an extension "yourFancyLister" this would be a new extension "yourFancyLister for bootstrap package".

This would provide all the necessary TypoScript-, Fluid-, CSS- and JS-changes necessary to make yourFancyLister work with the bootstrap package. But it would NEITHER touch the bootstrap package NOR yourFancyLister, so these could still be used independently from themes.

Of course you could do it in a more generic way and create a mini extension "yourFancyLister for theme bootstrap", which would make your extension aware of the base package only. So people could already use it with the default bootstrap settings and would have to take care of the actual theme settings in their CSS or in another mini extension.

The goal is to have the base packages (i.e. theme_bootstrap) provide as many things as generic standards as possible. Anything which is not generic anymore can then be created on the next level, the theme extension (i.e. theme_bootstrap_highland).

And anything which has to be specific beyond the theme level can then be provided by some mini extensions connecting i.e. the calendar base with a certain theme base or a particular theme. Each of them is inheriting from the others so you just have to provide things that should be different or don't exist yet.

This way we are reducing the actual workload to create themes with additional functionality to an absolute minimum.

**Comment by s-leger** [comment]
@kaystrobach 
Yes, looking at gridelements i've found the level of abstraction realy awsome.
As side note : Bootstrap package make use of a lib.dynamicContent and lib.dynamicContentSlide witch are realy great.


I know binding programmation to layout is a bad idea.
But with well known structured packages defining clear and stable layouts basis this dream can come true.

My goal (and i'm realy close) is to provide a way for typo generate images at the right size for any layout and any breakpoint.

To achieve this, we have to handle sizes from template layout then through gridelements, and finally to images.

The template parts columns width can be set via variables in fluid templates.
```
	<f:alias map="{col_md:9, col_lg:9}">
		<f:render partial="Content/Main" section="Default" arguments="{_all}" />
	</f:alias>
```
Passing those vars to typoscript libs:
```
<f:cObject typoscriptObjectPath="lib.content.main"  data="{col_xs:'{col_xs}',col_sm:'{col_sm}',col_md:'{col_md}',col_lg:'{col_lg}'}" />
```

The gridelement part is a bit more tricky. As we have to handle columns count and nesting of elements. But using registers allow this without any probs. Some changes in the way columns class are set in flexforms (multi columns containers), using integer instead of class names and wrap into generic classes at typoscript level. So it is possible to make generic processing of sizes.

As content frames sizes are defined by behiavours (mainly) this part is easy to handle, with appropriates variables to set the frames width. 

Binding grid size and frames borders/margins/padding variables to main packages via less is possible too, so there is only one place to setup.

**Comment by kaystrobach** [comment]
@s-leger we planned no to do it this way,  but use kind of Javascript size recognition and  / or additional src attributes to be fully responsive and flexible currently we just use the maxWidth defined in the core

Ps rendering like you mentioned was possible with TV Framework, so I know the pros and cons quite well.... 

Please use an issue just for one topic,  if you want to discuss the image rendering please open a new one

**Comment by kaystrobach** [comment]
@s-leger for the normal BE columns the core has the maxWidth setting already available. During rendering there needs to be done quite some math to recalculate the maxWidth of images. The functionality is in the TYPO3 core.

See 
* http://typo3.org/extensions/repository/view/templavoila_framework#
* http://templavoila.busynoggin.com/templates/utility-fces/columns/columns-the-concepts/

Maybe we can addopt the thoughts done there to reduce the skills needed.
Basicly this is register magick - or not @Bunnyfield ?

**Comment by kaystrobach** [comment]
as the initial request is IMHO solved i close it for now, feel free to reopen
